/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_blog_demo_jni_NativeCalc */

#ifndef _Included_com_blog_demo_jni_NativeCalc
#define _Included_com_blog_demo_jni_NativeCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_blog_demo_jni_NativeCalc
 * Method:    add
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_blog_demo_jni_NativeCalc_add
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_blog_demo_jni_NativeCalc
 * Method:    subtract
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_blog_demo_jni_NativeCalc_subtract
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_blog_demo_jni_NativeCalc
 * Method:    multiply
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_blog_demo_jni_NativeCalc_multiply
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_blog_demo_jni_NativeCalc
 * Method:    divide
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_blog_demo_jni_NativeCalc_divide
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
